micronaut.application.name=mn-task-mcp-server
micronaut.server.port=8080

micronaut.mcp.server.transport=HTTP
micronaut.mcp.server.info.name=Simple Task MCP Server
micronaut.mcp.server.info.version=0.1.0
